Add ResizeContainer props (#258)
* Fix package.json typecheck script

Previously, it printed `error TS6053: File 'src/*.ts' not found.`

* Disable "@typescript-eslint/no-empty-interface"

We'll use interfaces instead of intersections (&) to get shorter error
messages and make interface merging in user code possible.

* Add declarations.d.ts to tell TS we don't have types for react-merge-refs

* Add ResizeContainerProps